#!/usr/bin/env bash
# Install NGINX server, set 404 page
apt-get -y update
apt-get -y install nginx
sudo mkdir -p /var/www/html
sudo touch index.html
echo "Hello World!" > /var/www/html/index.html
sudo touch 404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '/server_name _/a location /redirect_me { return 301 https://www.alxafrica.com; }' /etc/nginx/sites-available/default
sed -i '/server_name _/a error_page 404 /404.html; location = /404.html {root /var/www/html/404.html/;internal; }' /etc/nginx/sites-available/default
service nginx restart
