#!/usr/bin/env bash
# sets up a new server and update it along with a custom header.
sudo apt-get update
sudo apt-get install -y nginx
sudo mkdir -p /var/www/html
chown -R $USER:$USER /var/www/html
sudo chmod 755 -R /var/www
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > index.html
sudo mv index.html /var/www/html


echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html
echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;
   
   root /var/www/html;
   index index.html;
   location /redirect_me {
      return 301 https://www.alxafrica.com;
   }
   error_page 404 /404.html;
   location /404.html{
      internal;
   }
}" > default
sudo mv -f default /etc/nginx/sites-available/default
sudo echo "user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;
events {
        worker_connections 768;
}
http {
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
        ssl_prefer_server_ciphers on;
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;
        gzip on;
        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
        add_header X-Served-By $HOSTNAME;
}" > nginx.conf
mv -f nginx.conf /etc/nginx/nginx.conf
sudo service nginx restart

